workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0
      xcode: 15.0
      java: 11
    scripts:
      - name: Update Gradle wrapper to compatible version
        script: |
          cd android
          ./gradlew wrapper --gradle-version=8.3
          cd ..
      - name: Remove pubspec.lock and clean caches
        script: |
          rm -f pubspec.lock
          flutter clean
          rm -rf ~/.pub-cache
          rm -rf build
          rm -rf .dart_tool
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --verbose
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
