workflows:
  android-build:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - name: Setup Flutter environment
        script: |
          #!/bin/bash
          set -e
          cd $CM_BUILD_DIR
          if [ ! -d "android" ]; then
            flutter create --platforms=android,ios .
          fi
      
      - name: Generate Splash Screen
        script: |
          #!/bin/bash
          set -e
          cd $CM_BUILD_DIR
          flutter pub run flutter_native_splash:create
      
      - name: Copy App Icons
        script: |
          #!/bin/bash
          set -e
          
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-mdpi"
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-hdpi"
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xhdpi"
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xxhdpi"
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xxxhdpi"
          
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_48.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-mdpi/ic_launcher.png"
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_72.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-hdpi/ic_launcher.png"
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_96.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png"
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_144.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png"
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_192.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"
          
          echo "✓ Icons copied"
      
      - name: Create Strings Resources
        script: |
          #!/bin/bash
          set -e
          
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/values"
          
          cat > "$CM_BUILD_DIR/android/app/src/main/res/values/strings.xml" << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <string name="app_name">STVR LiveTV</string>
          </resources>
          EOF
          
          echo "✓ Strings configured"
      
      - name: Configure AndroidManifest
        script: |
          #!/bin/bash
          set -e
          
          MANIFEST="$CM_BUILD_DIR/android/app/src/main/AndroidManifest.xml"
          
          cat > "$MANIFEST" << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
          
              <uses-permission android:name="android.permission.INTERNET"/>
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
          
              <application
                  android:label="@string/app_name"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher"
                  android:usesCleartextTraffic="true">
          
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
          
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
          
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2"/>
          
              </application>
          
          </manifest>
          EOF
          
          echo "✓ AndroidManifest.xml configured"
      
      - name: Install dependencies
        script: |
          #!/bin/bash
          set -e
          cd $CM_BUILD_DIR
          flutter clean
          rm -f pubspec.lock
          flutter pub get
      
      - name: Build APK
        script: |
          #!/bin/bash
          set -e
          cd $CM_BUILD_DIR
          flutter build apk --release
      
      - name: Rename APK
        script: |
          #!/bin/bash
          set -e
          
          VERSION=$(grep "version:" $CM_BUILD_DIR/pubspec.yaml | head -1 | awk '{print $2}' | cut -d+ -f1)
          
          RELEASE_APK="$CM_BUILD_DIR/build/app/outputs/flutter-apk/app-release.apk"
          RENAMED_APK="$CM_BUILD_DIR/build/app/outputs/flutter-apk/STVR-LiveTV-v$VERSION.apk"
          
          if [ -f "$RELEASE_APK" ]; then
            mv "$RELEASE_APK" "$RENAMED_APK"
            echo "✓ APK renamed to: STVR-LiveTV-v$VERSION.apk"
          fi
    
    artifacts:
      - build/app/outputs/flutter-apk/STVR-LiveTV-*.apk
