workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
