workflows:
  android-build:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - name: Setup Flutter environment
        script: |
          #!/bin/bash
          set -e
          cd $CM_BUILD_DIR
          if [ ! -d "android" ]; then
            flutter create --platforms=android,ios .
          fi
      
      - name: Copy App Icons
        script: |
          #!/bin/bash
          set -e
          
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-mdpi"
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-hdpi"
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xhdpi"
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xxhdpi"
          mkdir -p "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xxxhdpi"
          
          # Kopíruj ikony s presným mapovaním
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_48.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-mdpi/ic_launcher.png"
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_72.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-hdpi/ic_launcher.png"
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_96.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png"
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_144.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png"
          cp "$CM_BUILD_DIR/assets/icons/ic_launcher_192.png" "$CM_BUILD_DIR/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"
          
          echo "✓ Icons copied successfully"
      
      - name: Configure AndroidManifest
        script: |
          #!/bin/bash
          set -e
          
          MANIFEST="$CM_BUILD_DIR/android/app/src/main/AndroidManifest.xml"
          
          cat > "$MANIFEST" << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.example.stvr_mobile">
          
              <uses-permission android:name="android.permission.INTERNET"/>
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
          
              <application
                  android:label="STVR LiveTV"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher"
                  android:usesCleartextTraffic="true">
          
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
          
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
          
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2"/>
          
              </application>
          
          </manifest>
          EOF
          
          echo "✓ AndroidManifest.xml configured"
      
      - name: Install dependencies
        script: |
          #!/bin/bash
          set -e
          cd $CM_BUILD_DIR
          flutter clean
          rm -f pubspec.lock
          flutter pub get
      
      - name: Build APK
        script: |
          #!/bin/bash
          set -e
          cd $CM_BUILD_DIR
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
