workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.0
      xcode: 15.0
      java: 17
    scripts:
      - name: Backup current code
        script: |
          cp -r lib lib_backup
          cp pubspec.yaml pubspec_backup.yaml
          cp -r assets assets_backup 2>/dev/null || true
      
      - name: Create new Flutter app project
        script: |
          cd ..
          rm -rf otttelka_clean
          flutter create -t app otttelka_clean
          cd otttelka_clean
      
      - name: Restore backed up code
        script: |
          rm -rf lib
          cp -r ../clone/lib_backup lib
          cp ../clone/pubspec_backup.yaml pubspec.yaml
          cp -r ../clone/assets_backup assets 2>/dev/null || true
      
      - name: Get packages
        script: |
          flutter pub get
      
      - name: Build APK
        script: |
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    
    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
