workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0
      xcode: 15.0
      java: 17
    scripts:
      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
