workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.0
      xcode: 15.0
      java: 17
    triggering:
      events:
        - push
      branch:
        include_patterns:
          - main
    scripts:
      - name: Initialize Android directory
        script: |
          set -e
          rm -rf android build pubspec.lock .dart_tool
          
          # Vytvor Android základnú štruktúru
          mkdir -p android/app/src/main/kotlin/com/stvrtv/mobile
          mkdir -p android/app/src/main/res/{values,mipmap-hdpi,mipmap-mdpi,mipmap-xhdpi,mipmap-xxhdpi}
          mkdir -p android/gradle/wrapper
          
          # build.gradle (root)
          cat > android/build.gradle << 'GRADLE_ROOT'
          buildscript {
              ext.kotlin_version = '1.8.10'
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.1.0'
                  classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
              }
          }
          
          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          GRADLE_ROOT
          
          # settings.gradle
          cat > android/settings.gradle << 'GRADLE_SETTINGS'
          pluginManagement {
              repositories {
                  gradlePluginPortal()
                  google()
                  mavenCentral()
              }
          }
          
          plugins {
              id "com.android.application" version "8.1.0" apply false
              id "org.jetbrains.kotlin.android" version "1.8.10" apply false
          }
          
          include ':app'
          GRADLE_SETTINGS
          
          # app/build.gradle
          cat > android/app/build.gradle << 'GRADLE_APP'
          plugins {
              id "com.android.application"
              id "kotlin-android"
              id "dev.flutter.flutter-gradle-plugin"
          }
          
          android {
              compileSdk 34
              ndkVersion "27.0.12077973"
              
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_11
                  targetCompatibility JavaVersion.VERSION_11
              }
              
              kotlinOptions {
                  jvmTarget = '11'
              }
              
              defaultConfig {
                  applicationId "com.stvrtv.mobile"
                  minSdkVersion 24
                  targetSdkVersion 34
                  versionCode 1
                  versionName "1.0.0"
              }
              
              buildTypes {
                  release {
                      signingConfig signingConfigs.debug
                  }
              }
              
              sourceSets {
                  main.kotlin.srcDirs += 'src/main/kotlin'
              }
          }
          
          dependencies {
              implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.10"
          }
          GRADLE_APP
          
          # MainActivity.kt
          cat > android/app/src/main/kotlin/com/stvrtv/mobile/MainActivity.kt << 'KOTLIN_MAIN'
          package com.stvrtv.mobile
          
          import io.flutter.embedding.android.FlutterActivity
          
          class MainActivity: FlutterActivity() {
          }
          KOTLIN_MAIN
          
          # AndroidManifest.xml
          cat > android/app/src/main/AndroidManifest.xml << 'MANIFEST'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.stvrtv.mobile">
              
              <uses-permission android:name="android.permission.INTERNET" />
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
              
              <application
                  android:label="STVR LiveTV"
                  android:icon="@mipmap/ic_launcher"
                  android:usesCleartextTraffic="true">
                  
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
                  
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2" />
              </application>
          </manifest>
          MANIFEST
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Build APK
        script: |
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    
    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
