scripts:
  - name: Generate Android if missing
    script: |
      if [ ! -d "android" ]; then
        flutter create --platforms=android,ios .
      fi
  
  - name: Clean dependencies
    script: |
      flutter clean
      rm -f pubspec.lock
      flutter pub get
  
  - name: Build APK
    script: |
      flutter build apk --release
