workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.0
      xcode: 15.0
      java: 17
    scripts:
      - name: Clean Flutter caches
        script: |
          rm -f pubspec.lock
          flutter clean
          rm -rf ~/.pub-cache
          rm -rf build
          rm -rf .dart_tool
      - name: Create fresh Flutter structure
        script: |
          flutter create --force --org com.stvrtv --project-name mobile .
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com


