workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.22.0
      xcode: 15.0
      java: 17
    scripts:
      - name: Complete clean - DELETE EVERYTHING
        script: |
          rm -rf android .dart_tool build pubspec.lock ~/.pub-cache
          flutter clean

      - name: Get Flutter packages fresh
        script: |
          flutter pub get --no-offline

      - name: Regenerate Android from scratch
        script: |
          flutter create -t app --org com.stvrtv --project-name mobile . --force

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
