workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0

    scripts:
      - name: Clean and Regenerate Android folder
        script: |
          rm -rf android
          flutter create --platforms=android .

      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
