workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: 3.24.0
      android_signing:
        - keystore_reference
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
