workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0

    scripts:
      - name: Regenerate Android folder
        script: |
          if [ ! -d "android" ]; then
            echo "Android folder not found. Regenerating Flutter project..."
            flutter create --org com.stvrtv --project-name mobile .
          else
            echo "Android folder exists. Skipping regeneration."
          fi

      - name: Fetch dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
