workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.0
      xcode: 15.0
      java: 17
    scripts:
      - name: Full clean
        script: |
          rm -rf android build pubspec.lock .dart_tool
          flutter clean
      - name: Regenerate Android
        script: |
          python3 << 'EOF'
          import os
          import shutil
          
          os.system("flutter pub get")
          
          # Vytvor Android z Gradle template
          os.system("mkdir -p android/app/src/main/kotlin/com/stvrtv/mobile")
          os.system("mkdir -p android/app/src/main/res/mipmap-hdpi")
          
          # Vytvor AndroidManifest.xml
          manifest = '''<?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.stvrtv.mobile">
              <uses-permission android:name="android.permission.INTERNET" />
              <application
                  android:label="STVR LiveTV"
                  android:icon="@mipmap/ic_launcher">
                  <activity
                      android:name=".MainActivity"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2" />
              </application>
          </manifest>'''
          
          with open("android/app/src/main/AndroidManifest.xml", "w") as f:
              f.write(manifest)
          
          print("Android structure created!")
          EOF
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
