workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0
    scripts:
      - name: Remove pubspec.lock
        script: |
          rm -f pubspec.lock
      - name: Clean all caches
        script: |
          flutter clean
          rm -rf ~/.pub-cache
          rm -rf build
          rm -rf .dart_tool
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --verbose
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
