workflows:
  android-build:
    name: Android Build
    
    environment:
      flutter: stable
    
    scripts:
      - name: Setup Flutter environment
        script: |
          #!/bin/bash
          set -e
          
          # Presunieme sa do build priečinka
          cd $CM_BUILD_DIR
          
          # Vygeneruj Android ak neexistuje
          if [ ! -d "android" ]; then
            echo "Android directory not found, creating..."
            flutter create --platforms=android,ios .
            echo "Android directory created"
          fi
          
          # Skontroluj či existuje
          if [ -d "android" ]; then
            echo "✓ Android directory exists"
            ls -la android/ | head -5
          else
            echo "✗ Android directory still missing!"
            exit 1
          fi
      
      - name: Install dependencies
        script: |
          #!/bin/bash
          set -e
          cd $CM_BUILD_DIR
          flutter clean
          rm -f pubspec.lock
          flutter pub get
      
      - name: Build APK
        script: |
          #!/bin/bash
          set -e
          cd $CM_BUILD_DIR
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
