workflows:
  android-workflow:
    name: OttTelka Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.0
      xcode: 15.0
      java: 17
    scripts:
      - name: Clean and regenerate
        script: |
          rm -rf android .dart_tool build pubspec.lock
          flutter clean

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Regenerate Android
        script: |
          flutter create -t app --org com.stvrtv --project-name mobile . --no-offline

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - fieldydnb@gmail.com
